= Instalación
include::_attributes.adoc[]

[#instalacion]
== Instalación de OpenSCAP

Todo el lab se ejecutará en el mismo servidor, por ello vamos a instalar toda la paquetería en el mismo sistema (la imagen que hemos instalado ya tiene los paquetes necesarios por lo que no hace falta este paso,  lo hemos añadido para tener toda la información completa):

[IMPORTANT]
====
Para el laboratorio utilizar usuario **root** y password **redhat**.
====

[.lines_7]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
[root@client ~]# dnf install -y openscap-scanner scap-security-guide scap-workbench
----

El paquete *openscap-scanner* instala la herramienta _oscap_ desde la cual podremos lanzar los escaneos de compliance sobre nuestros sistemas, generar reports o incluso generar las remediaciones con Ansible.

El paquete *scap-security-guide* instala los **data streams** necesarios en la ruta _/usr/share/xml/scap/ssg/content/_. Este **data stream** contiene la información de todos los perfiles de SCAP con sus reglas asociadas para evaluar el compliance de un scan o también para generar las remediaciones. Esta información está en el fichero _XCCDF_ (Extensible Configuration Checklist Description File) _ssg-rhel9-xccdf.xml_.

Por último el paquete *scap-workbench* nos servirá para generar perfiles custom de compliance, como veremos más adelante. Solamente añadir que también permite evaluar el compliance en local y en sistemas remotos a través de _SSH_.

